image: microsoft/dotnet/core/sdk:2.1

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "dotnet build"
        - "dotnet test"