image: microsoft/dotnet:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "dotnet build"
        - "dotnet test"