// <auto-generated />
using System;
using MTGSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MTGSystem.Migrations
{
    [DbContext(typeof(MTGSystemContexto))]
    [Migration("20200910113003_UpdateToMTGSet")]
    partial class UpdateToMTGSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MTGSystem.Models.MTGSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AnoDeLancamento");

                    b.Property<string>("Nome");

                    b.Property<int>("QuantidadeDeCartas");

                    b.HasKey("Id");

                    b.ToTable("MTGSet");
                });
#pragma warning restore 612, 618
        }
    }
}
